const swaggerJsdoc = require("swagger-jsdoc");
const swaggerUi = require("swagger-ui-express");

const swaggerOptions = {
   definition: {
      openapi: "3.0.0",
      info: {
         title: "API Documentation",
         version: "1.0.0",
         description: "API documentation for frontend developers",
      },
      servers: [
         {
            url: `http://localhost:${process.env.PORT || 3000}`,
         },
      ],
      components: {
         schemas: {
            User: {
               type: "object",
               properties: {
                  id: {
                     type: "string",
                     description: "User ID (auto-generated by MongoDB)",
                     example: "65a1dcb1f5d4a32b1c8e5678",
                  },
                  username: {
                     type: "string",
                     description:
                        "Unique username (3-30 characters, only letters, numbers, underscores, and dots)",
                     example: "john_doe",
                  },
                  email: {
                     type: "string",
                     format: "email",
                     description: "User's unique email address",
                     example: "john.doe@example.com",
                  },
                  password: {
                     type: "string",
                     format: "password",
                     description:
                        "Hashed password (8-32 characters, must include uppercase, lowercase, number, special character)",
                     example: "hashed_password",
                  },
                  createdAt: {
                     type: "string",
                     format: "date-time",
                     description: "Timestamp when the user was created",
                     example: "2024-03-10T12:00:00Z",
                  },
                  updatedAt: {
                     type: "string",
                     format: "date-time",
                     description: "Timestamp when the user was last updated",
                     example: "2024-03-11T12:30:00Z",
                  },
               },
               required: ["username", "email", "password"],
            },
         },
      },
   },
   apis: ["./routes/*.js"],
};

const swaggerDocs = swaggerJsdoc(swaggerOptions);

module.exports = { swaggerUi, swaggerDocs };
